### PR TITLE
chore: move build system to poetry from setup.py

### LINKED ISSUE #33: Document local dev and add some basic scripts for working locally (makefile/justfile/whatever)
It'd be nice to have some docs on:

1. How to build the go/python to make sure its working
2. How to setup your vscode so that it can debug the go 
3. How to run tests and all that

If we have a makefile that does this it'd be great, but docs are good enough.

### PR DESCRIPTION
**Pull request by wwitzel3**
fixes #33 

- [x] ensure new system works with our GitHub Actions
- [x] document the poetry steps and local dev process in the `README.md`

### CODE REVIEW

**Comment by wwitzel3** [comment]
Tested with Release action - https://github.com/cloud-custodian/tfparse/actions/runs/3236059837

**Comment by wwitzel3** [comment]
@sontek give this a try and let me know if you run in to any issues on the Mac

**Comment by sontek** [comment]
Works great for me on `m1`

**Comment by kapilt** [comment]
nice!

**Pull request merged**
